#!/bin/bash

GN='\033[0;32m'
NC='\033[0m'

if [ -z "$IP" ]; then
	echo "Error: please set the IP envrionment variable for the test device."
	exit 1
fi

if [ -z "$SSHPASS" ]; then
	echo "Error: please set the SSHPASS envrionment variable for the test device."
	exit 1
fi

echo -e "${GN}Building for ARM64 RPI3 ...${NC}"
CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -tags termus -ldflags="-w -s" ./cmd/pebble
#./upx --best pebble

echo -e "${GN}Testing on device with IP=$IP ...${NC}"
sshpass -e ssh -q -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" root@$IP "/usr/bin/killall pebble 2> /dev/null"
sshpass -e ssh -q -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" root@$IP "/bin/mkdir -p /var/lib/pebble/default/layers"
sshpass -e scp -q -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" 001-base-layer.yaml root@$IP:/var/lib/pebble/default/layers/
sshpass -e scp -q -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" pebble root@$IP:/root/

